# Set various logging levels
loggers:
  engineio: 30

# Database connection parameters. Will be splatted, so therefore check out the
# valid parameters for the chosen database connection library (eg sqlite3,
# psycopg...).
database:
  database: busme
  user:
  host: '127.0.0.1'
  port: '5432'
  password:

# Various authentication parameters.
authentication:
  # API identifier. Should be listed in the dashboard under "identifier", and
  # should look like a URL (though it doesn't have to).
  # APIs > <API> > sidebar "API Audience"
  api_id:

  # Parameters to authenticate ID Token JWTs.
  id_token_params:
    # A list of acceptable algorithms for verifying JWTs. A list of available
    # algorithms is provided here:
    # https://pyjwt.readthedocs.io/en/latest/algorithms.html
    algorithms: ["RS256"]
    # Applications > <Application> > Settings > Client ID
    audience:
  
  # Parameters to verify Access Token JWTs.
  # Be sure to set RBA and default audience active (or some other way to get
  # JWT access tokens).
  access_token_params:
    algorithms: ["RS256"]
    audience:

  # OpenID configuration URI.
  # https://auth0.com/docs/protocols/oidc/openid-connect-discovery
  # https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata
  openid_discovery:

# Management API permissions mapping. As this app cannot dynamically generate
# permissions (or?) it is up to you to map these roles correctly, and ensure
# that they actually exist on both sides, or else a lot of people will be very
# unhappy.
permissions:
  create_organization: create:organization
  create_route: create:route

# SSL stuff (set to null to use plain HTTP, though you probably shouldn't)
ssl:
  # cert:
  # key:

# A list of folders where all the static files are located, if any.
# (should only be used in development)
static_files:

# Should the tables be dropped each time the server starts up?
db_startup_wipe: False
