platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!

target 'BusMe' do
  # ------------
  # REACT NATIVE
  # ------------

  rn_path = '../node_modules/react-native'
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]
  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"

  # ------------
  # DEPENDENCIES
  # ------------

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  pod 'A0Auth0', :path => '../node_modules/react-native-auth0'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-maps', :path => rn_maps_path
  pod 'react-native-google-maps', path: rn_maps_path
  pod 'Google-Maps-iOS-Utils'
  pod 'GoogleMaps'
  pod 'GooglePlaces'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  
end
